### ISSUE TITLE
the 1.5.40 linux_server is not useable on debian

### ISSUE THREAD

**Issue by z0sen** [BishopFox/sliver#1327]
**Describe the bug**
the newst 1.5.40 linux_server is not useable

**To Reproduce**
1. just run the program `./sliver-server_linux`
2. See error

**Expected behavior**
It should be start normally

**Screenshots**
<img width="782" alt="image" src="https://github.com/BishopFox/sliver/assets/49097104/467f0e67-321c-4f5f-933e-e6fbc57c7223">

**Desktop (please complete the following information):**
 - OS: debian 11
 - Version: 1.5.40

**Additional context**
$ ./sliver-server_linux 

Sliver  Copyright (C) 2022  Bishop Fox
This program comes with ABSOLUTELY NO WARRANTY; for details type 'licenses'.
This is free software, and you are welcome to redistribute it
under certain conditions; type 'licenses' for details.

Unpacking assets ...
stacktrace from panic: 
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
github.com/bishopfox/sliver/server/cli.glob..func4.1()
        github.com/bishopfox/sliver/server/cli/cli.go:119 +0x72
panic({0x17d41e0, 0xc01afa7400})
        runtime/panic.go:884 +0x213
github.com/bishopfox/sliver/server/cryptography.ECCServerKeyPair()
        github.com/bishopfox/sliver/server/cryptography/cryptography.go:303 +0xe5
github.com/bishopfox/sliver/server/cli.glob..func4(0xa424ce0?, {0x1a244c9?, 0x0?, 0x0?})
        github.com/bishopfox/sliver/server/cli/cli.go:127 +0x7a
github.com/spf13/cobra.(*Command).execute(0xa424ce0, {0xc00010e260, 0x0, 0x0})
        github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xa424ce0)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
github.com/bishopfox/sliver/server/cli.Execute()
        github.com/bishopfox/sliver/server/cli/cli.go:145 +0x25
main.main()
        github.com/bishopfox/sliver/server/main.go:43 +0x17

**Comment by rkervella** [comment]
If this is an update, make sure to remove the old `$HOME/.sliver` directory first. v1.5.40 is not backward compatible.

**Comment by moloch--** [comment]
Yea this is the backwards incompatibility bug, `rm -rf ~/.sliver` should fix it.

**Comment by sevagas** [comment]
Are you sure? It did not work from me. I removed .sliver it did not work. I also tried removing all sliver artifacts and reinstall with rm -rf ~/.sliver I still have the problem.
