### ISSUE TITLE
failed to perform armory install on windows

### ISSUE THREAD

**Issue by WhiteLee03** [BishopFox/sliver#1529]
Error output as below:
```
[*] Server v1.5.41 - xxx
[*] Welcome to the sliver shell, please type 'help' for options

[*] Check for updates with the 'update' command

sliver > armory -p socks5://127.0.0.1:10701 search hound

 Packages
 Command Name    Version   Type    Help                           URL
=============== ========= ======= ============================== =============================================
 sharp-hound-3   v0.0.2    Alias   C# based BloodHound Ingestor   https://github.com/sliverarmory/SharpHound3
 sharp-hound-4   v0.0.1    Alias   C# based BloodHound Ingestor   https://github.com/sliverarmory/SharpHound4

sliver > armory -p socks5://127.0.0.1:10701 install sharp-hound-3

[!] 
Failed to install file: empty file \SharpHound3.exe
[!] Failed to install alias 'sharp-hound-3': failed to install alias
```

My Windows Version: Microsoft Windows 10 (10.0.19045)

**Comment by WhiteLee03** [comment]
I performed armory install on my MacOs successfully, but on Windows failed🤨

**Comment by RafBishopFox** [comment]
It looks like this issue has been fixed since the current release version was built. Using a client binary built from the current `master` branch, installing aliases from the armory seems to work fine on Windows:
![image](https://github.com/BishopFox/sliver/assets/84349012/c7f353da-58fc-47a3-b563-8b2022c10ac8)
![image](https://github.com/BishopFox/sliver/assets/84349012/a6cbd3df-ce52-4dd6-bf8d-7d3ce5d3d3b0)
If you need this functionality before the next release, you could build a Windows client from the current source by running `make clients`.

**Comment by rkervella** [comment]
Duplicate, root cause (https://github.com/BishopFox/sliver/issues/1360) has been identified and fixed for the armory, there are other places where it's still an issue IIRC.
