### ISSUE TITLE
wg-socks implant crash

### ISSUE THREAD

**Issue by pooki3bear** [BishopFox/sliver#505]
**Describe the bug**
While attempting to use a (probably misconfigured) wg-socks session, the WG implant became entirely unresponsive, and eventually session lost. 

During the period before the session was lost, executing `wg-socks` from sliver-client made the client unresponsive.

**Expected behavior**
Expect `wg-socks` output to have a reasonable timeout, and provide some error instead of very slow timeout.

**Comment by moloch--** [comment]
Let us know if you find a reliable way to reproduce the issue. I suspect this is due to a blocking read() call or something.

**Comment by rkervella** [comment]
Yeah pretty sure it's the same bug that happens on the other cases, the server reading more bytes than expected and thus blocking.

**Comment by moloch--** [comment]
I think* this should be fixed in the `stage` branch.

**Comment by rkervella** [comment]
Hm doesn't seem so. `shell` still doesn't work, and the behavior seems similar.
